name: Terraform

on:
  push:
    branches:
      - main  # or any branch you want to trigger on

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # specify your Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        TF_VAR_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # or the name you used for the secret

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Terraform Output
      run: terraform output -json > terraform-output.json

    - name: Commit Terraform Output
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add terraform-output.json
        git commit -m "Add Terraform output"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
